<a href="https://colab.research.google.com/github/rmattos2001/config-repo/blob/master/TensorFlow_DL_Day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Tensors

In [ ]:
import tensorflow as tf
import numpy as np

Los tensores son arreglos multidimensionales con un tipo uniforme (llamado `dtype`). Puede ver todos los `dtypes` admitidos en `tf.dtypes.DType`.

Si está familiarizado con [NumPy](https://dphi.tech/lms/learn/introduction-to-numpy), los tensores son (más o menos) como `np.arrays`.

Todos los tensores son inmutables como los números y las cadenas de Python: nunca puede actualizar el contenido de un tensor, solo puede crear uno nuevo.



## Conceptos Basicos

Antes de crear tensores básicos, comprendamos algunos conceptos básicos. 

### **Scalar, Vector, Matrix 101**


![image name](https://dphi-courses.s3.ap-south-1.amazonaws.com/tensor.jpeg)

* A scalar es solo un numero
* A vector es un arreglo de numeros.
* A matrix is a 2-D array (arreglo bidimensional)
* A tensor is a n-dimensional array(arreglo n-bidimensional) with n >2 



###  **Comprensión de la Dimensión - Indexes - Rank - Axes - Shape**

1.   List item
2.   List item



####**Dimensión:** 

Tomemos un ejemplo de caja para explicar esto. Una caja simple puede tener tres dimensiones de ancho, largo y profundidad (o altura). De manera similar, en la ciencia de datos trabajaremos conjuntos de datos de "N" dimensiones. "N" podría ser cualquier número


![image name](https://dphi-courses.s3.ap-south-1.amazonaws.com/introduction-to-numpy/dimensions.png)




####**Indexes:** 

Indexes are required to access an element in a Data Structure.

![image name](https://dphi-courses.s3.ap-south-1.amazonaws.com/introduction-to-numpy/index+humans+and+python.png)

For example, suppose we have this array:

In [ ]:
a = [1,2,3,4]

Now, suppose we want to access (refer to) the number 3 in this data structure. We can do it using a single index like so:


In [ ]:
a[2]

3

In [ ]:
#As another example, suppose we have this 2d-array:
 
dd = [
[1,2,3],
[4,5,6],
[7,8,9]
] 

Now, suppose we want to access (refer to) the number 3 in this data structure. In this case, we need two indexes to locate the specific element.

In [ ]:
dd[0][2]

3




#### **Rank:** (rango)


El rango de un tensor se refiere al número de dimensiones presentes dentro del tensor.

**Rank & Indexes:**

El rango de un tensor nos dice cuántos índices se requieren para acceder (referirse a) un elemento de datos específico contenido dentro de la estructura de datos del tensor.

El rango de un tensor nos dice cuántos índices se necesitan para referirse a un elemento específico dentro del tensor.

####**Tensor Axes(Ejes) Ejemplo**
Veamos algunos ejemplos para hacer esto sólido. Consideraremos el mismo tensor dd que antes:

In [ ]:
dd = [
[1,2,3],
[4,5,6],
[7,8,9]
]

Each element along the first axis, is an array:

In [ ]:
dd[0]

[1, 2, 3]

In [ ]:
dd[1]

[4, 5, 6]

In [ ]:
dd[2]

[7, 8, 9]

Each element along the second axis, is a number:

In [ ]:
dd[0][0]

1

In [ ]:
dd[1][0]

4

In [ ]:
dd[2][0]

7

In [ ]:
dd[0][1]

2

In [ ]:
dd[1][1]

5

In [ ]:
dd[2][1]

8

In [ ]:
dd[0][2]

3

In [ ]:
dd[1][2]

6

In [ ]:
dd[2][2]

9

Tenga en cuenta que, con tensores, los elementos del último eje son siempre números. Cada otro eje contendrá matrices n-dimensionales. Esto es lo que vemos en este ejemplo, pero esta idea se generaliza.

El rango de un tensor nos dice cuántos ejes tiene un tensor, y la longitud de estos ejes nos lleva al concepto muy importante conocido como la forma de un tensor.

### **Shape(forma) of a Tensor**

La forma(shape) de un tensor está determinada por la longitud de cada eje, por lo que si conocemos la forma de un tensor dado, entonces conocemos la longitud de cada eje, y esto nos dice cuántos índices hay disponibles a lo largo de cada eje.

La forma de un tensor nos da la longitud de cada eje del tensor. Consideremos el mismo tensor dd que antes:

In [ ]:
# Let's say we have a 2D array
dd = [
[1,2,3],
[4,5,6],
[7,8,9]
]


In [ ]:
#To work with this tensor's shape, we’ll create a tensor object like so:

t = tf.constant(dd)      # constant() is a function that helps you create a constant tensor
t

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [ ]:
type(t)   # To get the type of object t

tensorflow.python.framework.ops.EagerTensor

In [ ]:
# Now, we have a Tensor object, and so we can ask to see the tensor's shape:

t.shape

TensorShape([3, 3])

# Tensor Operation Types
Antes de sumergirnos en operaciones de tensor específicas, obtengamos una descripción general rápida del panorama al observar las principales categorías de operaciones que abarcan las operaciones que cubriremos. Tenemos las siguientes categorías de operaciones de alto nivel:

1. Operaciones de remodelación
2. Operaciones elementales
3. Operaciones de reducción
4. Operaciones de acceso

## Reshaping A Tensor In TensorFlow - Remodelación de un tensor en TensorFlow

Veamos ahora todas las formas en que se puede remodelar este tensor ***t*** sin cambiar el rango:

Supongamos que tenemos el siguiente tensor:

In [ ]:
t = tf.constant([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=tf.float32)    # can also mention the type of the element we want in the tensor

In [ ]:
reshaped_tensor = tf.reshape(t, [1,12])     # reshape is a function that helps to reshaping any ndarray or ndtensor
print(reshaped_tensor)

tf.Tensor([[1. 1. 1. 1. 2. 2. 2. 2. 3. 3. 3. 3.]], shape=(1, 12), dtype=float32)


In [ ]:
reshaped_tensor = tf.reshape(t, [2,6])
print(reshaped_tensor)

tf.Tensor(
[[1. 1. 1. 1. 2. 2.]
 [2. 2. 3. 3. 3. 3.]], shape=(2, 6), dtype=float32)


In [ ]:
reshaped_tensor = tf.reshape(t, [3,4])
print(reshaped_tensor)

tf.Tensor(
[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]], shape=(3, 4), dtype=float32)


Usando la función ***`reshape()`***, podemos especificar la forma de fila x columna que estamos buscando. Observe cómo todas las formas tienen que dar cuenta de la cantidad de elementos en el tensor. En nuestro ejemplo esto es:


```
rows * columns = 12 elements
```



Podemos usar las palabras intuitivas filas y columnas cuando tratamos con un tensor de rango 2. La lógica subyacente es la misma para los tenores de dimensiones superiores, aunque es posible que no podamos usar la intuición de filas y columnas en espacios de dimensiones superiores. Por ejemplo:

In [ ]:
reshaped_tensor = tf.reshape(t, [2,2,3])
print(reshaped_tensor)

tf.Tensor(
[[[1. 1. 1.]
  [1. 2. 2.]]

 [[2. 2. 3.]
  [3. 3. 3.]]], shape=(2, 2, 3), dtype=float32)


En este ejemplo, aumentamos el rango a 3, por lo que perdemos el concepto de filas y columnas. Sin embargo, el producto de los componentes de la forma (2,2,3) todavía tiene que ser igual al número de elementos en el tensor original (12).

## Changing Shape By Squeezing And Unsqueezing - Cambiar de forma apretando y soltando
La siguiente forma en que podemos cambiar la forma de nuestros tensores es apretándolos***(Squeezing)*** y soltándolos***(Unsqueezing)***.

1. Al apretar un tensor se quitan las dimensiones o ejes que tienen una longitud de uno.
2. Descomprimir un tensor agrega una dimensión con una longitud de uno.

Estas funciones nos permiten ampliar o reducir el rango (número de dimensiones) de nuestro tensor. Veamos esto en acción.

In [ ]:
print(tf.reshape(t, [1,12]))

tf.Tensor([[1. 1. 1. 1. 2. 2. 2. 2. 3. 3. 3. 3.]], shape=(1, 12), dtype=float32)


In [ ]:
print(tf.reshape(t, [1,12]).shape)

(1, 12)


In [ ]:
# squeeze : longitud de uno
print(tf.squeeze(tf.reshape(t, [1,12])))

tf.Tensor([1. 1. 1. 1. 2. 2. 2. 2. 3. 3. 3. 3.], shape=(12,), dtype=float32)


In [ ]:
print(tf.squeeze(tf.reshape(t, [1,12])).shape)

(12,)


Veamos un caso de uso común para comprimir(***squeezing***) un tensor mediante la construcción de una ***función flatten***.

## Flatten A Tensor - Aplanar un tensor
Una operación de ***flatten(aplanamiento)*** en un tensor remodela el tensor para que tenga una forma que sea igual al número de elementos contenidos en el tensor. Esto es lo mismo que una matriz 1d de elementos.


```
Flattening a tensor means to remove all of the dimensions except for one.

Flattening un tensor significa eliminar todas las dimensiones excepto una.
```



Let’s create a Python function called `flatten()`:

In [ ]:
def flatten(t):
    t = tf.reshape(t, [1, -1])
    t = tf.squeeze(t)
    return t

The flatten() function takes in a tensor ***t*** as an argument.

Dado que el argumento ***t*** puede ser cualquier tensor, pasamos -1 como segundo argumento a la ***función reshape()***. En ***TensorFlow***, el -1 le dice a la ***función reshape()*** que averigüe cuál debe ser el valor según la cantidad de elementos contenidos dentro del tensor. Recuerda, la forma debe ser igual al producto de los valores de los componentes de la forma. Así es como ***TensorFlow*** puede averiguar cuál debería ser el valor, dado un 1 como primer argumento.

Dado que nuestro tensor ***t*** tiene 12 elementos, la ***función reshape()*** puede determinar que se requiere un 12 para la longitud del segundo eje(***axis***).

After squeezing, the first axis (axis-0) is removed, and we obtain our desired result, a 1d-array of length 12.

Here's an example of this in action:



In [ ]:
t = tf.ones([4, 3])
t

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
flatten(t)

<tf.Tensor: shape=(12,), dtype=float32, numpy=array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)>

## Concatenating Tensors - Tensores de Concatenación
Combinamos tensores usando la función `concat()`, y el tensor resultante tendrá una forma que depende de la forma de los dos tensores de entrada.

Supongamos que tenemos dos tensores:

In [ ]:
t1 = tf.constant([
    [1,2],
    [3,4]
])

t2 = tf.constant([
    [5,6],
    [7,8]
])

We can combine t1 and t2 row-wise (axis-0) in the following way:

In [ ]:
tf.concat((t1, t2), axis = 0)  # concat() helps you to concatenate two tensors according to the given axis

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]], dtype=int32)>

We can combine them column-wise (axis-1) like this:

In [ ]:
tf.concat((t1, t2), axis = 1)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 5, 6],
       [3, 4, 7, 8]], dtype=int32)>

Cuando concatenamos tensores, aumentamos el número de elementos contenidos en el tensor resultante. Esto hace que los valores de los componentes dentro de la forma (longitudes de los ejes(***axis***)) se ajusten para tener en cuenta los elementos adicionales.

In [ ]:
tf.concat((t1, t2), axis = 0).shape

TensorShape([4, 2])

In [ ]:
tf.concat((t1, t2), axis = 1).shape

TensorShape([2, 4])

# Conclusion About Reshaping Tensors - Conclusión sobre la remodelación de tensores

Ahora deberíamos tener una buena comprensión de lo que significa remodelar un tensor. Cada vez que cambiamos la forma de un tensor, se dice que estamos remodelando(***reshaping***) el tensor.

Reference: Deeplizard